1298 Logs
ramses-rf/ramses_rf pull request #137
Opened 2024-10-14 18:40 UTC by silverailscolo

found a few packets

2024-10-16 09:18 UTC, zxdavb requested changes

2024-10-16 09:18 UTC, zxdavb commented on tests/tests/parsers/code_1298.log
> +2024-10-10T22:59:41.307778 074  I --- 37:117647 --:------ 37:117647 1298 003 0001FF
Thanks for adding **code_1298.log** - a useful addition.

For the `I|1298|0001FF` - add: `# {'co2_level': 511}`

2024-10-16 20:41 UTC, silverailscolo commented on tests/tests/parsers/code_1298.log
> +2024-10-10T22:59:41.307778 074  I --- 37:117647 --:------ 37:117647 1298 003 0001FF
Also tried to RQ the CO2 using ramses_cc action. Works, added to log. 1298 done so far

2024-10-17 06:45 UTC, zxdavb requested changes

2024-10-17 06:45 UTC, zxdavb commented on src/ramses_tx/ramses.py
> +        RP: r"^00[0-9A-F]{4}$",
When the `RP` payload REGEX is the same as the `I`, then you don't add the RP, but you do need to have the `RQ`.

That is what this code (later in **ramses.py** does:
```python
for code in CODES_SCHEMA.values():  # map any RPs to (missing) I_s
    if RQ in code and RP not in code and I_ in code:
        code[RP] = code[I_]
```

So, please remove the `RP: r"^00[0-9A-F]{4}$",`

2024-10-17 06:45 UTC, zxdavb commented on tests/tests/parsers/code_1298.log
> +# requesting the current value
I suggest:
```
# Vasco HRU will RP to a contrived RQ
````

2024-10-17 06:52 UTC, zxdavb commented
Make these two changes, and we'll merge

2024-10-17 23:29 UTC, zxdavb approved these changes

2024-10-17 23:29 UTC, merged

2024-10-17 23:36 UTC, zxdavb commented
Thanks @silverailscolo