22F3 Parser
ramses-rf/ramses_rf pull request #138
Opened 2024-10-14 19:10 UTC by silverailscolo

Fan speed codes, Checks passed.

2024-10-16 09:15 UTC, zxdavb requested changes

2024-10-16 09:15 UTC, zxdavb commented on src/ramses_tx/parsers.py
> +    # .I --- 29:151550 29:237552 --:------ 22F3 007 00023C-0304-0000  # 60 mins (0x3C)
not needed

2024-10-16 09:15 UTC, zxdavb commented on src/ramses_tx/parsers.py
> +    # .I --- 29:123150 29:099029 --:------ 22F3 007 00020F-0006-0000  ("unknown fan_mode: 00")
please move this info into **tests/tests/parsers/code_22f3.log**

2024-10-16 09:15 UTC, zxdavb commented on src/ramses_tx/ramses.py
> +        I_: r"^00[0-9A-F]{4}(0000)[0-9A-F]{4}(00){6}$",
This has changes for `22F4` as well as `22F3` - please limit a PR to one command code only, unless absolutely required.

2024-10-16 09:15 UTC, zxdavb commented on tests/tests/parsers/code_22f3.log
> +2024-10-14T20:51:11.263018 049  I --- 29:091138 32:022222 --:------ 22F3 007 00021E04060000 # {'minutes': 30, 'flags': [0, 0, 0, 0, 0, 0, 1, 0], '_new_speed_mode': 'per_vent_speed', '_fallback_speed_
what affect does this have on your system? is it a boost - add your comment as to this somewhere here

2024-11-03 19:41 UTC, silverailscolo commented on tests/tests/parsers/code_22f3.log
> +2024-10-14T20:51:11.263018 049  I --- 29:091138 32:022222 --:------ 22F3 007 00021E04060000 # {'minutes': 30, 'flags': [0, 0, 0, 0, 0, 0, 1, 0], '_new_speed_mode': 'per_vent_speed', '_fallback_speed_
Yes, it is a <boost> to value <high> (0406) with a timer value inserted. Docs/REM button text say it lasts 30 mins.

2025-04-10 22:38 UTC, zxdavb approved these changes

2025-04-10 22:38 UTC, zxdavb commented on src/ramses_tx/ramses.py
> +        I_: r"^(00|63)(021E)?[0-9A-F]{4}([0-9A-F]{8})?$",  # VASCO D60 HRU: .I + 22F3 007 00 021E 0406 0000 (a timer)
These comment should be in the **tests/tests/parsers/code_22f3.log** file.

2025-04-10 22:38 UTC, merged