10D0 Parser
ramses-rf/ramses_rf pull request #140
Opened 2024-10-14 19:46 UTC by silverailscolo

No new logs for 10D0. Checks passed

2024-10-15 07:07 UTC, zxdavb commented
Do you have any `10D0` packets in a packet log to support your PR? I would expect to see them.

If so, they need to be added to **tests/tests/parsers/code_10d0.log**? They will, if they are different to the existing `W|10D0|00FF` packet:
```
2022-07-03T22:52:34.571579 045  W --- 37:171871 32:155617 --:------ 10D0 002 00FF          # {'reset_counter': True}
```

2024-10-15 11:13 UTC, silverailscolo commented
> They will, if they are different to the existing W|10D0|00FF packet:

They are identical, so I didn't add a copy

2024-10-15 14:01 UTC, silverailscolo commented
I received a new packet Filter Change Reply from the D60 after placing the ramses_esp nearby:
```
2024-10-15 12:33:55.595000 000 RQ --- 18:130140 32:022222 --:------ 10D0 001 00            # {}
2024-10-15 12:33:55.609000 --- RP --- 32:022222 18:130140 --:------ 10D0 006 00A9B6B90000  # {'days_remaining': 185}
```

Added to the 10D0 tests file.

2024-10-16 09:08 UTC, zxdavb requested changes

2024-10-16 09:08 UTC, zxdavb commented on src/ramses_tx/parsers.py
> +            )
My experience tells me that `FE`, like `FF`, is a sentinel value.

You will need to look at tomorrow's payload, to confirm that it changes from: `00FEFE79FFFF` to `00FDFE79FFFF`.

Otherwise, the dict should be (similar to):
```
{
  'days_remaining': None, 
  'days_lifetime': None, 
  'percent_remaining': 0.605
}
```

2024-10-16 09:08 UTC, zxdavb commented on src/ramses_tx/parsers.py
>      return result
```suggestion
    result: dict[str, bool | float | None]

    if msg.verb == W_:
        return {"reset_counter": payload[2:4] != "00"}

    result = {}

    if payload[2:4] not in ("FF", "FE"):
        result["days_remaining"] = int(payload[2:4], 16)

    if payload[4:6] not in ("FF", "FE"):
        result["days_lifetime"] = int(payload[4:6], 16)

    result["percent_remaining"] = hex_to_percent(payload[6:8])

    return result
```

2024-10-16 09:08 UTC, zxdavb commented on src/ramses_tx/parsers.py
>      return result
The above suggestion is for the entire block,

2024-10-16 10:59 UTC, zxdavb requested changes

2024-10-16 10:59 UTC, zxdavb commented on src/ramses_tx/parsers.py
>      return result
I think I wasn't clear - that code block was for the entire function.

2024-10-16 10:59 UTC, zxdavb commented on tests/tests/parsers/code_10d0.log
> +2024-10-15T12:33:13.731547 060 RP --- 37:153226 18:130140 --:------ 10D0 006 00FEFE79FFFF  # {'days_remaining': 153, 'days_lifetime': 254, 'percent_remaining': 0.605}
Will become: `# {'percent_remaining': 0.605}`

2024-10-16 22:25 UTC, silverailscolo commented on src/ramses_tx/parsers.py
> +            )
Seems correct. Today, the payload is exactly the same `00FEFE79FFFF` so no days. Code suggestion adopted.

2024-10-17 06:15 UTC, zxdavb approved these changes

2024-10-17 06:16 UTC, merged

2024-10-17 06:16 UTC, zxdavb commented
Thanks @silverailscolo