Tweak `2210` for ClimaRad
ramses-rf/ramses_rf pull request #151
Opened 2024-10-21 19:47 UTC by silverailscolo

Still experimental what these 3 values mean

2024-11-03 19:14 UTC, silverailscolo commented
@zxdavb can you review this?

2024-11-03 22:42 UTC, zxdavb commented
@silverailscolo I am sorry I have not reviewed your PRs - I am under the hammer with work at the moment, and another repo is consuming all my spare capacity  - please bear with me.

2024-11-04 07:56 UTC, silverailscolo commented
I support your prios. We'll get to it

2025-04-10 22:53 UTC, zxdavb requested changes

2025-04-10 22:53 UTC, zxdavb commented on src/ramses_tx/parsers.py
> +    }
don't cut out data if you don't know what it means

2025-04-10 22:53 UTC, zxdavb commented on src/ramses_tx/parsers.py
> +    }
other people need to see this data, so they can contribute to the corpus

2025-04-11 08:35 UTC, silverailscolo commented on src/ramses_tx/parsers.py
> +    }
The parser in current head is returning nothing at all, so I think we're not cutting out anything, and the assert didn't fit, so I took that out as advised earlier

2025-06-03 18:37 UTC, zxdavb approved these changes

2025-06-03 18:38 UTC, merged