Tweak `22F4` ClimaRad payload
ramses-rf/ramses_rf pull request #156
Opened 2024-11-03 21:13 UTC by silverailscolo

2025-04-10 22:55 UTC, zxdavb requested changes

2025-04-10 22:55 UTC, zxdavb commented on src/ramses_tx/parsers.py
> +        0x04: "4",  # "medium-high", or high?
i suggest keep the old values - please explain why you've chosen not to do that

2025-04-11 08:27 UTC, silverailscolo commented on src/ramses_tx/parsers.py
> +        0x04: "4",  # "medium-high", or high?
Passing along the word 'speed' in a non-English UI is not advised from i18n (internationalization). Can be added in UI by user if desired, harder to take it out. The label should make clear what a value means, so perhaps one would want to replace 'fan_info' in the UI with 'Speed'.

2025-04-18 09:31 UTC, silverailscolo commented on src/ramses_tx/parsers.py
> +        0x04: "4",  # "medium-high", or high?
Rolled back the existing strings, as requested.

2025-07-24 21:04 UTC, zxdavb requested changes, later dismissed

2025-07-24 21:04 UTC, zxdavb commented on src/ramses_tx/parsers.py
> +            payload = payload[:4] + payload[12:14]
The payload should be immutable, no?

2025-07-24 21:04 UTC, zxdavb commented on src/ramses_tx/parsers.py
> +    RATE_LOOKUP = {  # note: no i18n here, localize in application
no comment required

2025-07-25 11:12 UTC, silverailscolo commented on src/ramses_tx/parsers.py
> +            payload = payload[:4] + payload[12:14]
Now using an extra var `_pl`

2025-07-27 09:12 UTC, silverailscolo commented on src/ramses_tx/parsers.py
> +    RATE_LOOKUP = {  # note: no i18n here, localize in application
Removed this comment

2025-07-30 17:37 UTC, merged